-- GENERATED by supabase/scripts/build_seed.mjs from content/ — do not edit by hand.
-- Lesson catalogue only (names, refs); no Quran or hadith text is stored in the database.
insert into public.lessons (lesson_id, kind, ref, title, hadith_id, project_id, available, sort_order) values
  ('m01-w03-ikhlas', 'surah', '112', 'سورة الإخلاص + حديث برّ الوالدين', 'PLACEHOLDER-birr-alwalidayn', 'birr-3-acts', true, 10),
  ('pilot-day-1', 'surah', '112', 'سورة الإخلاص + حديث برّ الوالدين', 'PLACEHOLDER-birr-alwalidayn', null, true, 20),
  ('pilot-day-2', 'surah', '114', 'سورة الناس + حديث عن الكذب', 'PLACEHOLDER-al-kadhib', null, true, 30),
  ('pilot-day-3', 'surah', '113', 'سورة الفلق + حديث عن الغضب', 'PLACEHOLDER-al-ghadab', null, true, 40),
  ('m01-w03-day2', 'hadith', 'PLACEHOLDER-birr-alwalidayn', 'تقرير المشروع + حديث اليوم', 'PLACEHOLDER-birr-alwalidayn', 'birr-3-acts', true, 50),
  ('hadith-birr-alwalidayn', 'hadith', 'PLACEHOLDER-birr-alwalidayn', 'حديث برّ الوالدين', 'PLACEHOLDER-birr-alwalidayn', null, false, 60),
  ('hadith-al-kadhib', 'hadith', 'PLACEHOLDER-al-kadhib', 'حديث عن الكذب', 'PLACEHOLDER-al-kadhib', null, false, 70),
  ('hadith-al-ghadab', 'hadith', 'PLACEHOLDER-al-ghadab', 'حديث عن الغضب', 'PLACEHOLDER-al-ghadab', null, false, 80),
  ('weekly-review', 'review', 'weekly', 'المراجعة الأسبوعية', null, null, false, 90)
on conflict (lesson_id) do update set
  kind = excluded.kind,
  ref = excluded.ref,
  title = excluded.title,
  hadith_id = excluded.hadith_id,
  project_id = excluded.project_id,
  available = excluded.available,
  sort_order = excluded.sort_order;
