#!/usr/bin/env node
// Design tokens → Flutter + web. The single source is tokens/design-tokens.json.
//
//   node tokens/build.mjs          write the generated files
//   node tokens/build.mjs --check  exit 1 if any generated file is stale (CI)
//
// Outputs (never edit by hand):
//   app/lib/theme/app_tokens.g.dart        AppColors, AppRadii, LessonRadii,
//                                          AppShadows, LessonShadows, AppFontFamilies
//   web/src/styles/tokens.generated.css    Tailwind v4 @theme (colors, radius, shadow, font)
//   web/src/styles/tokens.generated.ts     the same values for code (SVG art, canvas)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(fs.readFileSync(path.join(root, 'tokens/design-tokens.json'), 'utf8'));
const HEADER = 'GENERATED by tokens/build.mjs from tokens/design-tokens.json — do not edit.';

// ── helpers ──
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-z])([0-9])/g, '$1-$2').toLowerCase();
const num = (n) => String(n);
const alphaByte = (a) => Math.round(a * 255);
const hex2 = (n) => n.toString(16).toUpperCase().padStart(2, '0');
const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));

const colorEntries = tokens.colors.flatMap((g) => Object.entries(g.tokens));
const colorByName = Object.fromEntries(colorEntries);
function resolveHex(name) {
  const t = colorByName[name];
  if (!t) throw new Error(`unknown color ref: ${name}`);
  if (t.ref) throw new Error(`nested color ref: ${name}`);
  return t;
}
function cssColor(t) {
  if (t.ref) {
    const base = resolveHex(t.ref);
    if (base.alpha !== undefined) throw new Error(`ref to translucent color: ${t.ref}`);
    return `rgb(${rgb(base.hex).join(' ')} / ${num(t.alpha)})`;
  }
  return t.alpha === undefined ? t.hex : `rgb(${rgb(t.hex).join(' ')} / ${num(t.alpha)})`;
}
const dartArgb = (hex, alpha = 1) => `0x${hex2(alphaByte(alpha))}${hex.slice(1).toUpperCase()}`;
const radiusValue = (v) => (typeof v === 'number' ? v : v.value);
const radiusNote = (v) => (typeof v === 'number' ? undefined : v.note);
const cssShadow = (layers) =>
  layers.map((l) => `${l.x}px ${l.y}px ${l.blur}px 0 rgb(${rgb(l.color).join(' ')} / ${num(l.alpha)})`).join(', ');

// ── Dart ──
function dart() {
  const out = [`// ${HEADER}`, '// dart format off', "import 'package:flutter/painting.dart';", ''];
  out.push(
    '/// Design tokens for غَرْسة — the single source of truth (CLAUDE.md §4).',
    '/// Values come from the approved design in `design/html`. No screen may',
    '/// hardcode a color, size, radius or shadow; add a token to',
    '/// tokens/design-tokens.json and run `node tokens/build.mjs` instead.',
    'abstract final class AppColors {',
  );
  tokens.colors.forEach((g, i) => {
    if (i) out.push('');
    out.push(`  // ${g.group}`);
    for (const [name, t] of Object.entries(g.tokens)) {
      const note = t.note ? ` // ${t.note}` : '';
      if (t.ref) out.push(`  static final Color ${name} = ${t.ref}.withValues(alpha: ${num(t.alpha)});${note}`);
      else out.push(`  static const Color ${name} = Color(${dartArgb(t.hex, t.alpha)});${note}`);
    }
  });
  out.push('}', '');

  const radiiClass = (cls, doc, groups) => {
    if (doc) out.push(`/// ${doc}`);
    out.push(`abstract final class ${cls} {`);
    groups.forEach((g, i) => {
      if (g.group) {
        if (i) out.push('');
        out.push(`  // ${g.group}`);
      }
      for (const [name, v] of Object.entries(g.tokens)) {
        const note = radiusNote(v) ? ` // ${radiusNote(v)}` : '';
        out.push(`  static const double ${name} = ${num(radiusValue(v))};${note}`);
      }
    });
    out.push('}', '');
  };
  radiiClass('AppRadii', null, tokens.radii.app);
  radiiClass('LessonRadii', '17–23 child app & live lesson radii (design values).', tokens.radii.lesson);

  const shadowClass = (cls, doc, shadows) => {
    if (doc) out.push(`/// ${doc}`);
    out.push(`abstract final class ${cls} {`);
    for (const [name, layers] of Object.entries(shadows)) {
      out.push(`  static const List<BoxShadow> ${name} = [`);
      for (const l of layers) {
        out.push(
          `    BoxShadow(color: Color(${dartArgb(l.color, l.alpha)}), offset: Offset(${num(l.x)}, ${num(l.y)}), blurRadius: ${num(l.blur)}),`,
        );
      }
      out.push('  ];');
    }
    out.push('}', '');
  };
  shadowClass('AppShadows', null, tokens.shadows.app);
  shadowClass('LessonShadows', '17–23 shadows (design values).', tokens.shadows.lesson);

  out.push('/// Font families (Google Fonts names) and CSS `line-height: normal` ratios.');
  out.push('abstract final class AppFontFamilies {');
  for (const [role, f] of Object.entries(tokens.fonts)) {
    out.push(`  static const String ${role} = '${f.family}'; // ${f.note}`);
    if (f.normalLineHeight !== undefined) {
      out.push(`  static const double ${role}NormalLineHeight = ${num(f.normalLineHeight)};`);
    }
  }
  out.push('}', '');
  return out.join('\n');
}

// ── Web (Tailwind v4 @theme + TS) ──
const FALLBACK = { body: 'system-ui, sans-serif', heading: '"Cairo", system-ui, sans-serif', ayah: 'serif', classical: 'serif' };

function css() {
  const out = [`/* ${HEADER} */`, '/* Only design tokens exist — Tailwind\'s default palette, radii, shadows and fonts are removed. */', '@theme {'];
  out.push('  --color-*: initial;');
  for (const g of tokens.colors) {
    out.push(`  /* ${g.group} */`);
    for (const [name, t] of Object.entries(g.tokens)) out.push(`  --color-${kebab(name)}: ${cssColor(t)};`);
  }
  out.push('', '  --radius-*: initial;');
  for (const [prefix, groups] of [['', tokens.radii.app], ['lesson-', tokens.radii.lesson]]) {
    for (const g of groups) {
      for (const [name, v] of Object.entries(g.tokens)) out.push(`  --radius-${prefix}${kebab(name)}: ${num(radiusValue(v))}px;`);
    }
  }
  out.push('', '  --shadow-*: initial;');
  for (const [prefix, shadows] of [['', tokens.shadows.app], ['lesson-', tokens.shadows.lesson]]) {
    for (const [name, layers] of Object.entries(shadows)) out.push(`  --shadow-${prefix}${kebab(name)}: ${cssShadow(layers)};`);
  }
  out.push('', '  --font-*: initial;');
  for (const [role, f] of Object.entries(tokens.fonts)) {
    out.push(`  --font-${role}: "${f.family}", ${FALLBACK[role] ?? 'sans-serif'};`);
  }
  out.push('}', '', ':root {');
  for (const [role, f] of Object.entries(tokens.fonts)) {
    if (f.normalLineHeight !== undefined) out.push(`  --line-height-${role}-normal: ${num(f.normalLineHeight)};`);
  }
  out.push('}', '');
  return out.join('\n');
}

function ts() {
  const colors = Object.fromEntries(colorEntries.map(([n, t]) => [n, cssColor(t)]));
  const flatRadii = (groups) => Object.fromEntries(groups.flatMap((g) => Object.entries(g.tokens)).map(([n, v]) => [n, radiusValue(v)]));
  const shadowMap = (s) => Object.fromEntries(Object.entries(s).map(([n, l]) => [n, cssShadow(l)]));
  const data = {
    colors,
    radii: flatRadii(tokens.radii.app),
    lessonRadii: flatRadii(tokens.radii.lesson),
    shadows: shadowMap(tokens.shadows.app),
    lessonShadows: shadowMap(tokens.shadows.lesson),
    fonts: Object.fromEntries(Object.entries(tokens.fonts).map(([r, f]) => [r, f.family])),
  };
  return `// ${HEADER}\nexport const tokens = ${JSON.stringify(data, null, 2)} as const;\n\nexport type ColorToken = keyof typeof tokens.colors;\n`;
}

const outputs = {
  'app/lib/theme/app_tokens.g.dart': dart(),
  'web/src/styles/tokens.generated.css': css(),
  'web/src/styles/tokens.generated.ts': ts(),
};

const check = process.argv.includes('--check');
let stale = 0;
for (const [rel, content] of Object.entries(outputs)) {
  const file = path.join(root, rel);
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) continue;
  if (check) {
    console.error(`stale: ${rel}`);
    stale++;
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`wrote ${rel}`);
  }
}
if (check) {
  if (stale) {
    console.error('Design tokens changed without regenerating. Run: node tokens/build.mjs');
    process.exit(1);
  }
  console.log('Generated token files are up to date.');
}
