// Builds supabase/seed.sql (the `lessons` catalogue) from content/ — the single
// source of truth. Names only (surah names from the Tanzil metadata, hadith
// topics): no Quran or hadith TEXT goes into the database.
//
//   node supabase/scripts/build_seed.mjs          # write seed.sql
//   node supabase/scripts/build_seed.mjs --check  # fail if seed.sql is stale (CI)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));

/** Launch content (review notes D): Al-Ikhlas, Al-Falaq, An-Nas; everything else locked. */
const LAUNCH_SURAHS = [112, 113, 114];

const meta = read('content/quran/quran_meta.json');
const surahName = (n) => {
  const s = meta.surahs.find((x) => x.surah === n);
  if (!s) throw new Error(`surah ${n} missing from quran_meta.json`);
  return s.name;
};
const hadith = read('content/hadith/hadith.json').hadith;
for (const h of hadith) {
  if (h.approved !== false && (h.text == null || h.takhrij == null)) {
    throw new Error(`hadith ${h.id}: approved without text/takhrij`);
  }
}

const lessonsDir = path.join(root, 'content/lessons');
const scripts = fs
  .readdirSync(lessonsDir)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((f) => read(`content/lessons/${f}`))
  // Surah lessons (with an intro) first, then follow-up days.
  .sort((a, b) => Number(!a.steps.some((x) => x.type === 'intro')) - Number(!b.steps.some((x) => x.type === 'intro')));

const rows = [];
let order = 0;
const coveredSurahs = new Set();
for (const s of scripts) {
  const intro = s.steps.find((x) => x.type === 'intro');
  const had = s.steps.find((x) => x.type === 'hadith_loop');
  const proj = s.steps.find((x) => x.type === 'project_assign' || x.type === 'project_report');
  if (intro) coveredSurahs.add(intro.surah);
  rows.push({
    lesson_id: s.lessonId,
    kind: intro ? 'surah' : 'hadith',
    ref: intro ? String(intro.surah) : (had?.hadithId ?? 'none'),
    title: s.title,
    hadith_id: had?.hadithId ?? null,
    project_id: proj?.projectId ?? null,
    available: true,
    sort_order: (order += 10),
  });
}
// Launch surahs without a lesson script yet → locked «قريبًا».
for (const n of LAUNCH_SURAHS) {
  if (coveredSurahs.has(n)) continue;
  rows.push({
    lesson_id: `surah-${n}`,
    kind: 'surah',
    ref: String(n),
    title: `سورة ${surahName(n)}`,
    hadith_id: null,
    project_id: null,
    available: false,
    sort_order: (order += 10),
  });
}
// Hadith topics (approved:false → locked; the text is never stored or shown).
for (const h of hadith) {
  rows.push({
    lesson_id: `hadith-${h.id.toLowerCase().replace(/^placeholder-/, '').replace(/[^a-z0-9-]/g, '-')}`,
    kind: 'hadith',
    ref: h.id,
    title: h.title,
    hadith_id: h.id,
    project_id: null,
    available: h.approved === true,
    sort_order: (order += 10),
  });
}
rows.push({
  lesson_id: 'weekly-review',
  kind: 'review',
  ref: 'weekly',
  title: 'المراجعة الأسبوعية',
  hadith_id: null,
  project_id: null,
  available: false, // until the weekly-review contract exists
  sort_order: (order += 10),
});

const q = (v) => (v === null ? 'null' : typeof v === 'boolean' || typeof v === 'number' ? String(v) : `'${String(v).replaceAll("'", "''")}'`);
const cols = ['lesson_id', 'kind', 'ref', 'title', 'hadith_id', 'project_id', 'available', 'sort_order'];
const sql = `-- GENERATED by supabase/scripts/build_seed.mjs from content/ — do not edit by hand.
-- Lesson catalogue only (names, refs); no Quran or hadith text is stored in the database.
insert into public.lessons (${cols.join(', ')}) values
${rows.map((r) => `  (${cols.map((c) => q(r[c])).join(', ')})`).join(',\n')}
on conflict (lesson_id) do update set
  ${cols.filter((c) => c !== 'lesson_id').map((c) => `${c} = excluded.${c}`).join(',\n  ')};
`;

const out = path.join(root, 'supabase/seed.sql');
if (process.argv.includes('--check')) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current !== sql) {
    console.error('supabase/seed.sql is stale — run: node supabase/scripts/build_seed.mjs');
    process.exit(1);
  }
  console.log('seed.sql up to date');
} else {
  fs.writeFileSync(out, sql);
  console.log(`wrote ${path.relative(root, out)} (${rows.length} lessons)`);
}
